# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.Rlprob_obs_hhs <- function(obs, prim, hh_sizes, q, n, Sn, Sp, T, M) {
    .Call(`_hhinfection_Rlprob_obs_hhs`, obs, prim, hh_sizes, q, n, Sn, Sp, T, M)
}

.Rlprob_obs <- function(obs, prim, hh_size, q, Sn, Sp, T, M) {
    .Call(`_hhinfection_Rlprob_obs`, obs, prim, hh_size, q, Sn, Sp, T, M)
}

.Rlprob_obs_pri <- function(obs, pri, hh_size, q, Sn, Sp) {
    .Call(`_hhinfection_Rlprob_obs_pri`, obs, pri, hh_size, q, Sn, Sp)
}

.Rlprob_sec_obs_pri <- function(obs, mis, pri, m, q, Sn, Sp) {
    .Call(`_hhinfection_Rlprob_sec_obs_pri`, obs, mis, pri, m, q, Sn, Sp)
}

.Rgdat <- function(max_hh, q) {
    .Call(`_hhinfection_Rgdat`, max_hh, q)
}

.Rg <- function(gdat, max_hh, k, m) {
    .Call(`_hhinfection_Rg`, gdat, max_hh, k, m)
}

